language: php
sudo: required
dist: focal
group: edge

matrix:
  include:
    - php: 7.4
      env: LARAVEL_VERSION=5.*
    - php: 7.4
      env: LARAVEL_VERSION=6.*
    - php: 7.4
      env: LARAVEL_VERSION=7.*
    - php: 7.4
      env: LARAVEL_VERSION=8.*
    - php: 8.0
      env: LARAVEL_VERSION=6.*
    - php: 8.0
      env: LARAVEL_VERSION=7.*
    - php: 8.0
      env: LARAVEL_VERSION=8.*
    - php: 8.0
      env: LARAVEL_VERSION=9.*
    - php: 8.1
      env: LARAVEL_VERSION=8.*
    - php: 8.1
      env: LARAVEL_VERSION=9.*

before_install:
  - composer self-update --stable -n
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n

install:
  - travis_retry composer install --prefer-dist -n -o

script:
  - vendor/bin/phpunit